# Generated by Django 5.0.4 on 2024-04-08 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userfollow'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfollow',
            name='following',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dest_following', to=settings.AUTH_USER_MODEL),
        ),
    ]
